#!/usr/bin/env python3
import argparse,hashlib,json,struct,sys
from pathlib import Path
import numpy as np
sys.path.insert(0,str(Path(__file__).resolve().parent))
from train import validate,canonical,digest
p=argparse.ArgumentParser();p.add_argument('--world',type=Path,required=True);p.add_argument('--training',type=Path,required=True);p.add_argument('--out',type=Path,required=True);p.add_argument('--kernel',type=Path,required=True);p.add_argument('--diagnostic',action='store_true');a=p.parse_args()
raw=a.world.read_bytes();w=json.loads(raw);ids=validate(w);idx={v:i for i,v in enumerate(ids)}
rbytes=(a.training/'training.json').read_bytes();r=json.loads(rbytes);gbytes=(a.training/'geometry.json').read_bytes();g=json.loads(gbytes)
assert r['world_sha256']==digest(raw) and r['geometry_sha256']==digest(gbytes)
assert r['trainer_sha256']==digest((Path(__file__).parent/'train.py').read_bytes())
assert r['passed'] and all(r['gates'].values()),'failed training is not a usable world'
assert a.diagnostic or (r['platform']=='kaggle_tpu' and r['devices'] and all(d['platform']=='tpu' for d in r['devices'])),'actual TPU evidence required'
assert ids==g['node_ids'];z=np.asarray(g['coordinates']);shadow=np.asarray(g['shadow']);basis=np.asarray(g['projection']['basis']);center=np.asarray(g['projection']['center'])
assert z.shape==(len(ids),48) and shadow.shape==(len(ids),4) and np.isfinite(z).all()
assert np.max(abs((z-center)@basis-shadow))<1e-5 and np.max(abs(basis.T@basis-np.eye(4)))<1e-5
metadata=bytearray();nodes=bytearray();edges=bytearray()
def meta(obj):
 b=canonical(obj);o=len(metadata);metadata.extend(b);return struct.pack('<II',o,len(b))
for i,n in enumerate(w['nodes']):
 coords=np.round(np.r_[z[i],shadow[i]]*1_000_000).astype(np.int64)
 assert np.max(abs(coords))<1_000_000_000
 nodes+=meta(n)+struct.pack('<52i',*coords)
for e in w['edges']:
 edges+=struct.pack('<HHBbBB',idx[e['source']],idx[e['target']],w['relations'][e['relation']],e['polarity'],['train','validation','sealed_test','cross_composition','regression'].index(e['split']),0)+meta(e)
header=struct.pack('<8sHHHHI32s32s',b'ATLCNET2',len(ids),len(w['edges']),48,w['version'],len(metadata),bytes.fromhex(digest(raw)),bytes.fromhex(digest(rbytes)))
pack=header+nodes+edges+metadata
assert not a.out.exists();a.out.mkdir(parents=True)
for name,data in [('world.bin',pack),('world.json',raw),('geometry.json',gbytes),('training.json',rbytes)]: (a.out/name).write_bytes(data)
manifest=dict(schema=2,world_id=w['id'],version=w['version'],status='local_diagnostic' if a.diagnostic else 'accelerator_validated',sealed=False,passive=True,full_dimensions=48,observer_axes=['x','y','z','w'],source_sha256=digest(raw),files={name:digest((a.out/name).read_bytes()) for name in ['world.bin','world.json','geometry.json','training.json']})
(a.out/'manifest.json').write_bytes(canonical(manifest)+b'\n')
a.kernel.mkdir(parents=True,exist_ok=True)
# Embed exactly this versioned pack. The loader validates its compiled identity.
(a.kernel/'world.bin').write_bytes(pack)
code='//! Generated by network-lightcone/tools/finalize.py; provenance in versioned pack.\n'
code+='pub const PACK: &[u8] = include_bytes!("world.bin");\n'
code+='pub const HASH: [u8;32] = '+repr(list(bytes.fromhex(digest(pack))))+';\n'
for i,name in enumerate(ids): code+=f'pub const {name.upper()}: usize = {i};\n'
(a.kernel/'embedded.rs').write_text(code)
print(json.dumps(manifest,indent=2))
