#!/usr/bin/env python3
"""Pre-render DejaVu fonts into anti-aliased glyph bitmaps for the desktop.

Writes desktop/src/font_data.rs. DejaVu fonts are derived from Bitstream
Vera and may be embedded and redistributed (see the DejaVu license).
Usage: python3 scripts/gen-font.py   (needs Pillow and fonts-dejavu-core)
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
FONTS = "/usr/share/fonts/truetype/dejavu/"
STYLES = [  # (Rust name, file, pixel size)
    ("UI", "DejaVuSans.ttf", 13),
    ("UI_BOLD", "DejaVuSans-Bold.ttf", 13),
    ("MONO", "DejaVuSansMono.ttf", 13),
    ("TITLE", "DejaVuSans-Bold.ttf", 20),
    ("LARGE", "DejaVuSans.ttf", 32),
]
FIRST, LAST = 32, 126
# Non-ASCII glyphs used by the interface, stored after the ASCII range.
EXTRA = "\u00b7\u2022\u2026\u2014\u00d7\u00b0"

def render(file, size):
    font = ImageFont.truetype(FONTS + file, size)
    ascent, descent = font.getmetrics()
    glyphs, data = [], bytearray()
    for ch in [chr(c) for c in range(FIRST, LAST + 1)] + list(EXTRA):
        advance = round(font.getlength(ch))
        box = font.getbbox(ch)
        w, h = max(0, box[2] - box[0]), max(0, box[3] - box[1])
        image = Image.new("L", (max(w, 1), max(h, 1)), 0)
        if w and h:
            ImageDraw.Draw(image).text((-box[0], -box[1]), ch, font=font, fill=255)
        glyphs.append((len(data), w, h, box[0], box[1], advance))
        if w and h:
            data += image.tobytes()
    return ascent, descent, glyphs, data

out = ["// Generated by scripts/gen-font.py from DejaVu fonts (Bitstream Vera",
       "// derived; free to embed and redistribute). Do not edit by hand.",
       "use crate::font::{Font, Glyph};", ""]
for name, file, size in STYLES:
    ascent, descent, glyphs, data = render(file, size)
    out.append(f"static {name}_BITMAP: [u8; {len(data)}] = [{','.join(map(str, data))}];")
    out.append(f"static {name}_GLYPHS: [Glyph; {len(glyphs)}] = [")
    for offset, w, h, x, y, advance in glyphs:
        out.append(f"    Glyph {{ offset: {offset}, width: {w}, height: {h}, x: {x}, y: {y}, advance: {advance} }},")
    out.append("];")
    out.append(f"pub static {name}: Font = Font {{ ascent: {ascent}, descent: {descent}, first: {FIRST}, "
               f"glyphs: &{name}_GLYPHS, bitmap: &{name}_BITMAP, extra: {EXTRA!r} }};".replace("'", '"'))
    out.append("")
(ROOT / "desktop/src/font_data.rs").write_text("\n".join(out))
print("wrote", ROOT / "desktop/src/font_data.rs")
