[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
kernel-kit = { path = "../kernel-kit" }
kernel-orchestrator = { path = "../kernel-orchestrator" }
kernel-sense = { path = "../kernel-sense" }
kernel-key = { path = "../kernel-key", features = ["std"] }
kernel-instant = { path = "../kernel-instant", features = ["std"] }
kernel-egress = { path = "../kernel-egress", features = ["std"] }
kernel-lane = { path = "../kernel-lane", features = ["std"] }
kernel-taint = { path = "../kernel-taint", features = ["std"] }
kernel-crypt = { path = "../kernel-crypt", features = ["std"] }
kernel-net = { path = "../kernel-net", features = ["std"] }

[[bin]]
name = "e21"
path = "src/bin/e21.rs"

[[bin]]
name = "e22"
path = "src/bin/e22.rs"

[[bin]]
name = "e23"
path = "src/bin/e23.rs"

[[bin]]
name = "e24"
path = "src/bin/e24.rs"

[[bin]]
name = "e25"
path = "src/bin/e25.rs"

[[bin]]
name = "e31"
path = "src/bin/e31.rs"

[[bin]]
name = "e34"
path = "src/bin/e34.rs"

[[bin]]
name = "e35"
path = "src/bin/e35.rs"

[[bin]]
name = "e36"
path = "src/bin/e36.rs"

[[bin]]
name = "e37"
path = "src/bin/e37.rs"
